[package]
name = "roast2d_derive"
version = "0.0.1"
edition = "2021"
authors = ["jjy"]
description = "Roast2D derive macros"
license = "MIT"
repository = "https://github.com/jjyr/roast2d"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
